# Generated by Django 6.0.1 on 2026-02-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0002_task_ai_insight_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="document_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assignment",
            name="document_text_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
